idf_component_register(
    SRCS "main.c"
         "badge/badge.c"
         "badge/badge_data.c"
         "badge/badge_power.c"
         "badge/badge_ui.c"
         "game/game.c"
         "settings/settings.c"
         "transport/ble.c"
         "assets/badge_font_gb2312.c"
         "assets/badge_font_gb2312_small.c"
         "assets/badge_avatar.c"
    INCLUDE_DIRS "."
         "badge"
         "game"
         "settings"
         "transport"
         "assets"
    REQUIRES bsp ui esp_timer nvs_flash bt
)